### ISSUE TITLE
Build failured with Ubuntu 18.04 + LLVM 11.1 + latest ISPC release tag (1.15.0)

### ISSUE THREAD

**Issue by xkszltl** [ispc/ispc#2027]
Error log:

```
[162/257] Building CXX object CMakeFiles/ispc.dir/src/ctx.cpp.o
FAILED: CMakeFiles/ispc.dir/src/ctx.cpp.o
ccache /usr/local/bin/clang++ -DBUILD_DATE=\"20210223\" -DBUILD_VERSION="\"commit 003c44985ad9db15\"" -DISPC_ANDROID_TARGET_OFF -DISPC_ARM_ENABLED -DISPC_FREEBSD_TARGET_OFF -DISPC_IOS_TARGET_OFF -DISPC_MACOS_TARGET_OFF -DISPC_PS4_TARGET_OFF -DISPC_WINDOW
S_TARGET_OFF -DISPC_X86_ENABLED -DLLVM_11_1 -D_FORTIFY_SOURCE=2 -I/include -I../src -I. -fdebug-prefix-map='/tmp/scratch'='/usr/local/src' -g -O3  -Wall -Wno-sign-compare -Wno-unused-function -Werror -I/usr/local/include -D_GNU_SOURCE -D_DEBUG -D__STDC_C
ONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fstack-protector-strong -fdata-sections -ffunction-sections -fno-delete-null-pointer-checks -Wformat -Wformat-security -fpie -fwrapv -Wno-c99-extensions -Wno-deprecated-register -fno-rtti -std=
c++14 -MD -MT CMakeFiles/ispc.dir/src/ctx.cpp.o -MF CMakeFiles/ispc.dir/src/ctx.cpp.o.d -o CMakeFiles/ispc.dir/src/ctx.cpp.o -c ../src/ctx.cpp
../src/ctx.cpp:1699:33: error: no member named 'get' in 'llvm::ElementCount'
            llvm::ElementCount::get(static_cast<unsigned int>(g->target->getVectorWidth()), false), const_val);
            ~~~~~~~~~~~~~~~~~~~~^
../src/ctx.cpp:3203:60: error: no member named 'get' in 'llvm::ElementCount'
        llvm::ConstantVector::getSplat(llvm::ElementCount::get(static_cast<unsigned int>(ty->getNumElements()), false),
                                       ~~~~~~~~~~~~~~~~~~~~^
2 errors generated.
[163/257] Building CXX object CMakeFiles/ispc.dir/src/opt.cpp.o
FAILED: CMakeFiles/ispc.dir/src/opt.cpp.o
ccache /usr/local/bin/clang++ -DBUILD_DATE=\"20210223\" -DBUILD_VERSION="\"commit 003c44985ad9db15\"" -DISPC_ANDROID_TARGET_OFF -DISPC_ARM_ENABLED -DISPC_FREEBSD_TARGET_OFF -DISPC_IOS_TARGET_OFF -DISPC_MACOS_TARGET_OFF -DISPC_PS4_TARGET_OFF -DISPC_WINDOW
S_TARGET_OFF -DISPC_X86_ENABLED -DLLVM_11_1 -D_FORTIFY_SOURCE=2 -I/include -I../src -I. -fdebug-prefix-map='/tmp/scratch'='/usr/local/src' -g -O3  -Wall -Wno-sign-compare -Wno-unused-function -Werror -I/usr/local/include -D_GNU_SOURCE -D_DEBUG -D__STDC_C
ONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fstack-protector-strong -fdata-sections -ffunction-sections -fno-delete-null-pointer-checks -Wformat -Wformat-security -fpie -fwrapv -Wno-c99-extensions -Wno-deprecated-register -fno-rtti -std=
c++14 -MD -MT CMakeFiles/ispc.dir/src/opt.cpp.o -MF CMakeFiles/ispc.dir/src/opt.cpp.o.d -o CMakeFiles/ispc.dir/src/opt.cpp.o -c ../src/opt.cpp
../src/opt.cpp:1448:49: error: no member named 'get' in 'llvm::ElementCount'
                            llvm::ElementCount::get(
                            ~~~~~~~~~~~~~~~~~~~~^
../src/opt.cpp:1469:49: error: no member named 'get' in 'llvm::ElementCount'
                            llvm::ElementCount::get(
                            ~~~~~~~~~~~~~~~~~~~~^
../src/opt.cpp:2769:41: error: no member named 'get' in 'llvm::ElementCount'
                    llvm::ElementCount::get(
                    ~~~~~~~~~~~~~~~~~~~~^
3 errors generated.
ninja: build stopped: subcommand failed.
```

**Comment by dbabokin** [comment]
That's correct, it's not supported to. LLVM 11.1 was released after ISPC 1.15.0, so it was not tested and there are known problems with it (fixed in trunk). I suggest using LLVM 11.0, which is no different from LLVM 11.1 for the purpose of being ISPC backend.

**Comment by dbabokin** [comment]
Just in case - the problem is on ISPC side with not correctly using ISPC_LLVM_VERSION define. With 11.1 everything should be treated exactly as for 11.0, but it does not.

**Comment by xkszltl** [comment]
How about tagging a new release that works with 11.1, or provides a list of commit which can be backported to 1.15?

We have other components depending on llvm 11.1.
Do want to have too many custom-build llvm in system to make things complicated.
