### ISSUE TITLE
Openmoonray fails to compile with version 1.28.0

### ISSUE THREAD

**Issue by gonsolo** [ispc/ispc#3545]
Trying to compile [Openmoonray](https://github.com/dreamworksanimation/openmoonray)
with the patch from https://github.com/dreamworksanimation/openmoonray/discussions/192, I have this error:

> /usr/src/debug/ispc/ispc/src/ast.cpp:367: Assertion failed: "node->IsTypeChecked() && "Node must be type-checked before optimization"".
> ***
> *** Please file a bug report at https://github.com/ispc/ispc/issues
> *** (Including as much information as you can about how to reproduce this error).
> *** You have apparently encountered a bug in the compiler that we'd like to fix!
> ***
> /usr/src/debug/ispc/ispc/src/main.cpp(40): FATAL ERROR: Unhandled signal sent to process; terminating.
> /usr/src/debug/ispc/ispc/src/ast.cpp:367: Assertion failed: "node->IsTypeChecked() && "Node must be type-checked before optimization"".
> ***
> *** Please file a bug report at https://github.com/ispc/ispc/issues
> *** (Including as much information as you can about how to reproduce this error).
> *** You have apparently encountered a bug in the compiler that we'd like to fix!
> ***
> /usr/src/debug/ispc/ispc/src/main.cpp(40): FATAL ERROR: Unhandled signal sent to process; terminating.

which I can reproduce with

> cd /home/gonsolo/src/openmoonray/gonsolo/moonray/moonray/lib/rendering/shading/ispc && /home/gonsolo/src/ispc/gonsolo/bin/ispc -DGL_GLEXT_PROTOTYPES=1 -DNO_16BYTE_ATOMIC_LOCK_FREE -DPLATFORM_LINUX -DPLATFORM_UNIX -DTBB_SUPPRESS_DEPRECATED_MESSAGES -D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR=1 -D_LIBCPP_ENABLE_CXX17_REMOVED_RANDOM_SHUFFLE=1 -D_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION -D__AVX__ -D__cdecl="" @CMakeFiles/shading_ispc_02.dir/includes_ISPC.rsp -O3 -DNDEBUG --target=avx2-i32x8 --opt=force-aligned-memory --pic --wno-perf --opt=disable-assertions -M -MT moonray/moonray/lib/rendering/shading/ispc/CMakeFiles/shading_ispc_02.dir/bsdf/ashikhmin_shirley/BsdfAshikhminShirley.ispc.o -MF CMakeFiles/shading_ispc_02.dir/bsdf/ashikhmin_shirley/BsdfAshikhminShirley.ispc.o.d -o CMakeFiles/shading_ispc_02.dir/bsdf/ashikhmin_shirley/BsdfAshikhminShirley.ispc.o --emit-obj /home/gonsolo/src/openmoonray/moonray/moonray/lib/rendering/shading/ispc/bsdf/ashikhmin_shirley/BsdfAshikhminShirley.ispc -h /home/gonsolo/src/openmoonray/gonsolo//moonray/moonray/lib/rendering/shading/ispc/bsdf/ashikhmin_shirley/BsdfAshikhminShirley_ispc_stubs.h

Bisecting from 1.27 to 1.28 leads to this commit:

> gonsolo gonsolo:g bisect good
> 2e874c47282cbe284e069e50e6bf4bbaffa63488 is the first bad commit
> commit 2e874c47282cbe284e069e50e6bf4bbaffa63488
> Author: Arina Neshlyaeva <arina.neshlyaeva@intel.com>
> Date:   Mon Jun 2 16:32:25 2025 -0700
> 
>     Introduce TypeCheckAndOptimize()

Apparently not everything was typechecked before optimization.

**Comment by gonsolo** [comment]
This fixes the issue:

```
From 34076d71e740812c4e71d338211ae7287b04f645 Mon Sep 17 00:00:00 2001
From: Gon Solo <gonsolo@gmail.com>
Date: Sat, 16 Aug 2025 21:19:39 +0200
Subject: [PATCH] Fix Openmoonray.

---
 src/ast.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/ast.cpp b/src/ast.cpp
index f4c66b6e..bdc19c7e 100644
--- a/src/ast.cpp
+++ b/src/ast.cpp
@@ -364,7 +364,7 @@ static ASTNode *lOptimizeNode(ASTNode *node, void *) {
         return node;
     }
 
-    Assert(node->IsTypeChecked() && "Node must be type-checked before optimization");
+    //Assert(node->IsTypeChecked() && "Node must be type-checked before optimization");
 
     // Mark that we're starting the optimization process for this node
     node->StartOptimize();
-- 
2.50.1

```

**Comment by gonsolo** [comment]
After that it fails with:

> /home/gonsolo/src/ispc/src/expr.cpp:4862: Assertion failed: "ptrType != nullptr".
> ***
> *** Please file a bug report at https://github.com/ispc/ispc/issues
> *** (Including as much information as you can about how to reproduce this error).
> *** You have apparently encountered a bug in the compiler that we'd like to fix!

which is caused by commit:

> commit 536c26d7ba3d607ebaca427a69231dd1af76d796
> Author: Jérôme Richard <jeromerichard111@msn.com>
> Date:   Tue Jun 24 03:44:37 2025 +0200
> 
>     Fix #3439: function calls returning a pointer type is treated as an lvalue

**Comment by gonsolo** [comment]
This is the patch for the second issue:

```
From 87913aab2ddc356d38fe13934befda84b43cf247 Mon Sep 17 00:00:00 2001
From: Gon Solo <gonsolo@gmail.com>
Date: Sat, 16 Aug 2025 22:20:48 +0200
Subject: [PATCH 2/2] Fix Openmoonray II.

---
 src/expr.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/expr.cpp b/src/expr.cpp
index 43e453c9..b19a1f7e 100644
--- a/src/expr.cpp
+++ b/src/expr.cpp
@@ -4341,7 +4341,7 @@ const Type *FunctionCallExpr::GetLValueType() const {
         return nullptr;
     }
     const FunctionType *ftype = CastType<FunctionType>(type);
-    if (ftype && ftype->GetReturnType()->IsReferenceType()) {
+    if (ftype && (ftype->GetReturnType()->IsPointerType() || ftype->GetReturnType()->IsReferenceType())) {
         return ftype->GetReturnType();
     } else {
         // Only be a valid LValue type if the function returns a reference
-- 
2.50.1

```

**Comment by nurmukhametov** [comment]
Thank you for reporting this!

The minimal reproducer:

```ispc
struct E;
struct S {
    const uniform E *uniform f;
};
void foo(varying S *uniform x) {
    x->f = 0;
}
```

Compiler explorer link: https://ispc.godbolt.org/z/cnj4z4E1a

**Comment by gonsolo** [comment]
> [nurmukhametov](https://github.com/nurmukhametov) moved this from Todo to In Progress

Thanks, I'm eagerly waiting for 1.28.1! :)

**Comment by nurmukhametov** [comment]
> Thank you for reporting this!
> 
> The minimal reproducer:
> 
> struct E;
> struct S {
>     const uniform E *uniform f;
> };
> void foo(varying S *uniform x) {
>     x->f = 0;
> }
> Compiler explorer link: https://ispc.godbolt.org/z/cnj4z4E1a

After fixing this, I have realized that these two issue are independent, so I have created separate issues to track them:

- [x] #3547
- [x] #3549

**Comment by nurmukhametov** [comment]
> > [nurmukhametov](https://github.com/nurmukhametov) moved this from Todo to In Progress
> 
> Thanks, I'm eagerly waiting for 1.28.1! :)

I started releasing v1.28.1.

**Comment by nurmukhametov** [comment]
> > > [nurmukhametov](https://github.com/nurmukhametov) moved this from Todo to In Progress
> > 
> > 
> > Thanks, I'm eagerly waiting for 1.28.1! :)
> 
> I started releasing v1.28.1.

It has been released.
