### ISSUE TITLE
dev-lang/ispc-1.8.2: .../InstIterator.h: No such file or directory

### ISSUE THREAD

**Issue by toralf** [ispc/ispc#1096]
4. Add $LLVM_HOME/bin-3.5/bin path to your PATH. 
 ==============================================================================
echo Updating dependencies
Updating dependencies
x86_64-pc-linux-gnu-g++ -MM -march=native -O2 -pipe -I/usr/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I. -Iobjs/ -I/usr/include -DLLVM_3_3 -Wall -DBUILD_DATE="\"20150909\"" -DBUILD_VERSION="\""no_version_info"\"" -Wno-sign-compare -Wno-unused-function -Werror ast.cpp builtins.cpp cbackend.cpp ctx.cpp decl.cpp expr.cpp func.cpp ispc.cpp llvmutil.cpp main.cpp module.cpp opt.cpp stmt.cpp sym.cpp type.cpp util.cpp | sed 's_^\([a-z]\)_objs/\1_g' > depend
cbackend.cpp:71:36: fatal error: llvm/IR/InstIterator.h: No such file or directory
   #include "llvm/IR/InstIterator.h"
                                    ^

details are in https://bugs.gentoo.org/show_bug.cgi?id=560038

**Comment by junghans** [comment]
Fixed in `master` branch, so please create new release.

**Comment by dbabokin** [comment]
I'm not sure how you compile ISPC, but you are doing it incorrectly. You are adding LLVM 3.5 to the path, but using -DLLVM_3_3 macro, which is obviously incorrect and almost for sure leads to this problem.

**Comment by dbabokin** [comment]
If you use ispc Makefile as is, it will detect LLVM version you are using and you won't get such problem.

**Comment by junghans** [comment]
The line
```
4.) Add $LLVM_HOME/bin-3.5/bin path to your PATH. 
```
is part of the ispc warning from its Makefile.

I researched the issue a little bit on the gentoo site and it boils down to the fact that ispc-1.8.2 does not compile with llvm-3.3 anymore.

**Comment by dbabokin** [comment]
v1.8.2 has a problem building with LLVM 3.3, thought it's fixed in trunk.

Also it's NOT recommended to build with stock LLVM 3.3 due to multiple known issues (folder llvm_patches has fixes for these problems, but still).

v1.8.2 binaries are shipped with LLVM 3.6 and it's recommended LLVM version, though 3.4 and 3.5 are also ok.
