### ISSUE TITLE
Assertion with "-M -MF file" and multi-target

### ISSUE THREAD

**Issue by dbabokin** [ispc/ispc#1647]
```
> ispc t.ispc -M -MF t.d --target=avx512skx-i32x8,avx2-i32x8
/Users/dybaboki/ispc/dbabokin_ispc/src/util.cpp:619: Assertion failed: "filepath != nullptr".
***
*** Please file a bug report at https://github.com/ispc/ispc/issues
*** (Including as much information as you can about how to reproduce this error).
*** You have apparently encountered a bug in the compiler that we'd like to fix!
***
/Users/dybaboki/ispc/dbabokin_ispc/src/main.cpp(352): FATAL ERROR: Unhandled signal sent to process; terminating.
Abort trap: 6
```

**Comment by dbabokin** [comment]
Looks like it's regression after bc930b7f303c5579a999ff4b29b7a16378615046

**Comment by aneshlya** [comment]
This is fixed since [v1.13.0](https://github.com/ispc/ispc/releases/tag/v1.13.0)
