### ISSUE TITLE
Tests fail on FreeBSD with return code -11

### ISSUE THREAD

**Issue by yurivict** [ispc/ispc#2244]
ISPC tests fail on FreeBSD:
```
Running 8 jobs in parallel. Running 1543 tests.
Test ./tests/test-24.ispc failed (return code -11)                    
Test ./tests/typedef-4.ispc failed (return code -11)                  
Test ./tests/gather-int32-4.ispc failed (return code -11)             
Test ./tests/int64-min-1.ispc failed (return code -11)                
Test ./tests/cfor-test-77.ispc failed (return code -11)               
Test ./tests/funcptr-uniform-4.ispc failed (return code -11)            
Test ./tests/local-atomics-6.ispc failed (return code -11)            
Test ./tests/padds-i16.ispc failed (return code -11)                  
```

Version: 1.17.0
FreeBSD 13

**Comment by dbabokin** [comment]
More info on how the compiler is built is needed. What LLVM was used?

Are these the only tests that fail?

**Comment by yurivict** [comment]
> More info on how the compiler is built is needed. What LLVM was used?

LLVM-13 is used.


> Are these the only tests that fail?

All tests fail the same way.

**Comment by dbabokin** [comment]
Well, then it's a broken build.

We don't support FreeBSD out of the box, because we don't have FreeBSD machines available to us. Help with debugging is appreciated.

**Comment by dbabokin** [comment]
I'm trying to build ISPC on FreeBSD and it seems that there's a problem with platform identification, as it returns "amd64", while on Linux it's "AMD64".

But I have another problem with `m4`, which seems very old (`/usr/bin/m4`). When installing `m4` package (`pkg install m4`), I don't see any other m4 executable in the system (it's not in `/usr/local/bin`). Any hints how to install proper m4 on the system?

**Comment by yurivict** [comment]
@dbabokin 
The ```m4``` package installs the ```gm4``` executable.

There is a port for ISPC.
You can easily build it:
1. Check out the ports tree: git clone https://git.FreeBSD.org/ports.git /usr/ports
2. cd /usr/ports/devel/ispc
3. Install dependencies: pkg install -A `make missing`
4. Build: make

**Comment by dbabokin** [comment]
I fixed all the issues that I found on FreeBSD. Now it should build of the box and tests should pass. Please let me know if you have any other issues.

Also would be good to have it in CI, but FreeBSD is a rare beast in cloud services. TravisCI has 12.1 images available, which I'm going to try. Though I was not able to make it work on 12.1 locally, as it's EOL and some packages do not work, namely Python doesn't work. My local build was in 12.2.

**Comment by yurivict** [comment]
@dbabokin 

I applied all 5 patched to 1.17.0 but there is one failure:
```
/disk-samsung/freebsd-ports/devel/ispc/work/ispc-1.17.0/src/module.cpp:111:2: error: "Unexpected platform"
#error "Unexpected platform"
 ^
/disk-samsung/freebsd-ports/devel/ispc/work/ispc-1.17.0/src/module.cpp:1243:68: error: use of undeclared identifier 'OCLOC_LIBRARY_NAME'
    auto oclocLib = llvm::sys::DynamicLibrary::getPermanentLibrary(OCLOC_LIBRARY_NAME);
                                                                   ^
/disk-samsung/freebsd-ports/devel/ispc/work/ispc-1.17.0/src/module.cpp:1245:44: error: expected ')'
        Error(SourcePos(), "Cannot open '" OCLOC_LIBRARY_NAME "'\n");
                                           ^
/disk-samsung/freebsd-ports/devel/ispc/work/ispc-1.17.0/src/module.cpp:1245:14: note: to match this '('
        Error(SourcePos(), "Cannot open '" OCLOC_LIBRARY_NAME "'\n");
             ^
3 errors generated.
```

**Comment by dbabokin** [comment]
Looks like you are trying to build with `XE_ENABLED`, which doesn't make sense on FeeBSD, as Intel doesn't hasn't have [L0](https://github.com/oneapi-src/level-zero) and [compute-runtime](https://github.com/intel/compute-runtime) for FreeBSD.

**Comment by yurivict** [comment]
There's the ```L0``` port:
```
$ pkg search level-zero
level-zero-1.7.9               oneAPI Level Zero Specification Headers and Loader
```

and there are ```compute-runtime``` ports:
```
$ pkg search compute-runtime 
intel-compute-runtime-llvm11-22.04.22286 OpenCL implementation for Intel HD 5000 (Gen8) or newer
intel-compute-runtime-llvm12-22.04.22286 OpenCL implementation for Intel HD 5000 (Gen8) or newer
```

**Comment by dbabokin** [comment]
Well, if you are willing to enable GPU build on FreeBSD, we can do that, but my recommendation would be not to do that at the moment. GPU build requires specific versions of all components (see the details in the [Release Notes](https://github.com/ispc/ispc/releases/tag/v1.17.0)). If the versions are different (both older and newer), then it either will not work at all, or will be buggy. Going forward, as things get more stable, we should have more flexibility for version of our dependencies. But right now it's in active development stage and we have what we have.

**Comment by yurivict** [comment]
XE_ENABLED option doesn't have to be enabled, but at the same time it could be buildable.

**Comment by dbabokin** [comment]
Fair enough. Let's make it building, so I'm reopening the issue.

But please don't build with `XE_ENABLED` by default, it will likely lead to wasting time for people who will dare to play with it.

**Comment by yurivict** [comment]
Ok, I'll leave XE_ENABLED=OFF by default.

**Comment by yurivict** [comment]
There's also [this](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=261735) regression with the above patches.

**Comment by dbabokin** [comment]
This means you are building LLVM on your own, instead of using recommended way (using our `alloy.py` script and hence applying all recommended patches and recommended options).

To fix that, you need to either enabled ARM backend in LLVM (adding to LLVM's CMake `-DLLVM_TARGETS_TO_BUILD=AArch64;ARM`) or disabling ARM backend in ISPC (ISPC's CMake switch `-DARM_ENABLED=OFF`).

**Comment by dbabokin** [comment]
I was poking at Xe support on FreeBSD and figured out that it's a bit more changes than just changing a few switches. And at this point I would say I very reluctant to finalize and commit this, as I really don't know how this will work and I have no way to test it end-to-end.

I suggest asking a customer what is the use for ISPC with Xe support. We don't have too many customers for Xe targets at this point. The feature is being actively developed and many things are unstable. If the customer wants to build "just in case", we should not support that. Anyway, we will not be able to fix any FreeBSD specific bugs related to Xe at this point.

**Comment by pbrubaker** [comment]
Closing this issue as resolved based on Dmitry's comment.
