### ISSUE TITLE
Doesn't build with current llvm (v3.6)

### ISSUE THREAD

**Issue by stolk** [ispc/ispc#1078]
$ llvm-config --version
3.6.0

$ make
Updating dependencies
In file included from <built-in>:320:
<command line>:6:17: error: whitespace recommended after macro name [-Werror]
#define LLVM_3_6.0 1
                ^
In file included from ast.cpp:40:
In file included from ./ast.h:41:
./ispc.h:44:2: error: "Only LLVM 3.1, 3.2, 3.3 and the 3.4 development branch are supported"
#error "Only LLVM 3.1, 3.2, 3.3 and the 3.4 development branch are supported"

**Comment by dbabokin** [comment]
We build with 3.6.2. But this definitely needs to be fixed.

Recommended way to build ISPC is to build with manually pre-built LLVM (using alloy.py script).

**Comment by ncos** [comment]
Could you please execute './ispc -v'? It looks like you are trying to use an old version of ISPC, the latest (trunk version) is 1.8.3dev

**Comment by stolk** [comment]
This canned response does not apply.
Read the report: i am trying to build ispc.
From repository src.

On Monday, August 3, 2015, Anton Mitrokhin <notifications@github.com> wrote:

> Could you please execute './ispc -v'? It looks like you are trying to use
> an old version of ISPC, the latest (trunk version) is 1.8.3dev
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ispc/ispc/issues/1078#issuecomment-127177933>.
>


-- 

“Programming today is a race between software engineers striving to build
bigger and better idiot- proof programs, and the Universe trying to produce
bigger and better idiots. So far, the Universe is winning.” (R Cook).

**Comment by dbabokin** [comment]
The problem is that your error message look outdated (note that only versions up to 3.4 are mentioned).

Current error message is (ispc.h:44):
#error "Only LLVM 3.2, 3.3, 3.4, 3.5, 3.6, 3.7 and 3.8 development branch are supported"

And this mismatch is confusing. Please double check your version.

**Comment by stolk** [comment]
github.com:mmp/ispc.git is not the latest?


$ cat .git/config
[core]
    repositoryformatversion = 0
    filemode = true
    bare = false
    logallrefupdates = true
[remote "origin"]
    url = git@github.com:mmp/ispc.git
    fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
    remote = origin
    merge = refs/heads/master

bram@ubuntu64:~/src/ispc$ git pull
Already up-to-date.

bram@ubuntu64:~/src/ispc$ make
Updating dependencies
In file included from <built-in>:320:
<command line>:6:17: error: whitespace recommended after macro name
[-Werror]
#define LLVM_3_6.0 1
                ^
In file included from ast.cpp:40:
In file included from ./ast.h:41:
./ispc.h:44:2: error: "Only LLVM 3.1, 3.2, 3.3 and the 3.4 development
branch are supported"
#error "Only LLVM 3.1, 3.2, 3.3 and the 3.4 development branch are
supported"

$ grep ISPC_VERSION ispc.h
#define ISPC_VERSION "1.5.1dev"



On Mon, Aug 3, 2015 at 9:54 AM, Dmitry Babokin <notifications@github.com>
wrote:

> The problem is that your error message look outdated (note that only
> versions up to 3.4 are mentioned).
>
> Current error message is (ispc.h:44):
> #error "Only LLVM 3.2, 3.3, 3.4, 3.5, 3.6, 3.7 and 3.8 development branch
> are supported"
>
> And this mismatch is confusing. Please double check your version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ispc/ispc/issues/1078#issuecomment-127330143>.
>



-- 

“Programming today is a race between software engineers striving to build
bigger and better idiot- proof programs, and the Universe trying to produce
bigger and better idiots. So far, the Universe is winning.” (R Cook).

**Comment by dbabokin** [comment]
Official trunk is https://github.com/ispc/ispc.git
