### PR TITLE
Bunch of fixes related to LLVM 20.1 and LLVM trunk.

### LINKED ISSUE #3282: Error when building with llvm 20.1.0
platform: slackware64-current
llvm: 20.1.0

when building the latest [ispc from slackbuilds.org](https://slackbuilds.org/repository/15.0/development/ispc/) with the newer llvm (20.1.0) this error manifests:
```
-- The C compiler identification is Clang 20.1.0
-- The CXX compiler identification is Clang 20.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- LLVM_CONFIG_EXECUTABLE: /usr/bin/llvm-config
-- LLVM_TOOLS_BINARY_DIR: /usr/bin
-- LLVM_DIR is /usr/bin/../lib/cmake/llvm
-- CLANG_EXECUTABLE: /usr/bin/clang
-- CLANGPP_EXECUTABLE: /usr/bin/clang++
-- LLVM_AS_EXECUTABLE: /usr/bin/llvm-as
-- FILE_CHECK_EXECUTABLE: /usr/bin/FileCheck
-- Detected LLVM version: 20.1.0
-- GIT_BINARY: /usr/bin/git
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- M4 macro processor: /usr/bin/m4
-- Found Python3: /usr/bin/python3.12 (found version "3.12.9") found components: Interpreter
-- Found BISON: /usr/bin/bison (found suitable version "3.8.2", minimum required is "3.0")
-- Found FLEX: /usr/bin/flex (found suitable version "2.6.4", minimum required is "2.6")
-- BITCODE_FOLDER is /tmp/SBo/ispc-1.26.0/build/bin/../share/ispc
-- Enabling target: linux / i686
-- Enabling target: linux / x86_64
-- ISPC will be built as a composite binary
-- ISPC Runtime will be built with support of TBB tasking model on CPU
-- Found TBB: 2021.10.0 at /usr/lib64/cmake/TBB
-- Configuring done (1.7s)
-- Generating done (0.2s)
CMake Warning:
  Manually-specified variables were not used by the project:

    LIB_SUFFIX
    MAN_INSTALL_DIR


-- Build files have been written to: /tmp/SBo/ispc-1.26.0/build
[...]
[ 48%] Building CXX object CMakeFiles/frontend.dir/src/module.cpp.o
/tmp/SBo/ispc-1.26.0/src/module.cpp:1182:45: error: no member named 'getWithCaptureInfo' in 'llvm::Attribute'
 1182 |                         i, llvm::Attribute::getWithCaptureInfo(function->getContext(), llvm::CaptureInfo::none()));
      |                            ~~~~~~~~~~~~~~~~~^
/tmp/SBo/ispc-1.26.0/src/module.cpp:1182:107: error: no member named 'none' in 'llvm::CaptureInfo'
 1182 |                         i, llvm::Attribute::getWithCaptureInfo(function->getContext(), llvm::CaptureInfo::none()));
      |                                                                                        ~~~~~~~~~~~~~~~~~~~^
2 errors generated.
make[2]: *** [CMakeFiles/frontend.dir/build.make:219: CMakeFiles/frontend.dir/src/module.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:601: CMakeFiles/frontend.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
let me know if I can add further info.

### PR DESCRIPTION
**Pull request by aneshlya**
1. Update LLVM 20.1 tag to llvmorg-20.1.0
2. Fix build with LLVM trunk and LLVM 20.1
3. Update SDE version
4. Update token permissions
Fixes #3282

### CODE REVIEW

**Review by dbabokin — APPROVED** [review]
LGTM

**Review by nurmukhametov — APPROVED** [review]
LGTM!
