### ISSUE TITLE
Export function returning pointer to structure in v1.7.0 fails to compile.

### ISSUE THREAD

**Issue by tkoziara** [ispc/ispc#803]
Try to compile:

struct data
{
  uniform int i[8];
  uniform float d[8];
  uniform data \* uniform next;
};
export uniform data \* uniform data_create (uniform int size)
{
  uniform data \* uniform p = uniform new uniform data [size];
  return p;
}

and you'll get:

Function return type does not match operand type of return inst!
  ret %v4_uniform_data\* %ret_value8
 %v8_uniform_data*Broken module found, compilation aborted!
main.cpp(225): FATAL ERROR: Unhandled signal sent to process; terminating.

This however worked in v1.4.4.

**Comment by pbrubaker** [comment]
It appears this specific issue isn't reproducing anymore.  We still have an issue with structs returned by value being incorrect.
