### ISSUE TITLE
ispc does not compile with llvm 2.9

### ISSUE THREAD

**Issue by uzytkownik** [ispc/ispc#114]
The offending commit is 2460fa5c:

```
opt.cpp:1765:43: warning: unused variable ‘svInstType’ [-Wunused-variable]
opt.cpp:1847:14: warning: unused variable ‘sizeKnown’ [-Wunused-variable]
opt.cpp:1895:71: error: no matching function for call to ‘llvm::PHINode::Create(const llvm::Type*&, unsigned int&, const char [4], llvm::PHINode*&)’
opt.cpp:1895:71: note: candidates are:
/usr/include/llvm/Instructions.h:1829:19: note: static llvm::PHINode* llvm::PHINode::Create(const llvm::Type*, const llvm::Twine&, llvm::Instruction*)
/usr/include/llvm/Instructions.h:1829:19: note:   candidate expects 3 arguments, 4 provided
/usr/include/llvm/Instructions.h:1833:19: note: static llvm::PHINode* llvm::PHINode::Create(const llvm::Type*, const llvm::Twine&, llvm::BasicBlock*)
/usr/include/llvm/Instructions.h:1833:19: note:   candidate expects 3 arguments, 4 provided
opt.cpp: In member function ‘virtual bool GSImprovementsPass::runOnBasicBlock(llvm::BasicBlock&)’:
opt.cpp:2443:14: warning: unused variable ‘ok’ [-Wunused-variable]
opt.cpp: In member function ‘virtual bool LowerGSPass::runOnBasicBlock(llvm::BasicBlock&)’:
opt.cpp:2693:14: warning: unused variable ‘ok’ [-Wunused-variable]
make: *** [objs/opt.o] Error 1
```
