### ISSUE TITLE
Support LLVM-16

### ISSUE THREAD

**Issue by MehdiChinoune** [ispc/ispc#2513]
It fails to build against LLVM-16
```
ispc/src/ispc-1.20.0/src/opt.cpp:176:15: error: no type named 'initializeInstrumentation' in namespace
'llvm'
        llvm::initializeInstrumentation(*registry);
        ~~~~~~^
ispc/src/ispc-1.20.0/src/opt.cpp:233:25: error: no member named 'createPruneEHPass' in namespace 'llvm'
        optPM.add(llvm::createPruneEHPass());
                  ~~~~~~^
2 errors generated.
```

**Comment by MehdiChinoune** [comment]
> It's not supposed to work with LLVM 16.0. Only LLVM 13.0-15.0 are supported. Released version has limitation baked in the source:
> 
> https://github.com/ispc/ispc/blob/14bd04aa7e68cd33eb1d96b33058cb64d7ef76f4/src/ispc_version.h#L37

No,
https://github.com/ispc/ispc/blob/main/src/ispc_version.h#L37

**Comment by dbabokin** [comment]
Yes, it's know issue, which requires moving to new pass manager and using alternative passes. This support will be merged soon, but it's a complex move.
