### ISSUE TITLE
Error introduced by #636

### ISSUE THREAD

**Issue by jbrodman** [ispc/ispc#644]
#636 introduced a compilation error.

The following example compiles before this commit:

```
struct Baz {
       int stuff;
       float moreStuff;
};

struct Foo {
  Baz base;
  unsigned int width;
};

struct Bar {
  Foo base;
  unsigned int height;
};


int func(const uniform Foo *uniform foo_) {
  const uniform unsigned int height = 500;
  int res;
  for (uniform int y = 0; y < height; y++) {
    uniform float tmp = sin((y+0.5f)*rcp((float)height));
    res = tmp;
  }
  return res;
}
```

After this commit, the following error is generated:
bug.ispc:21:38: Error: Multiple overloaded functions matched call to function "rcp".
        Passed types: (/_unbound_/ float)
        Candidate: /_safe_/ varying float(varying float)
        Candidate: /_safe_/ uniform float(uniform float)
    uniform float tmp = sin((y+0.5f)*rcp((float)height));
                                     ^^^

bug.ispc:21:38: Error: Valid function name must be used for function call.
    uniform float tmp = sin((y+0.5f)*rcp((float)height));
                                     ^^^^^^^^^^^^^^^^^^
