### ISSUE TITLE
1.12.0 build fails: error: expected type

### ISSUE THREAD

**Issue by yurivict** [ispc/ispc#1567]
```
===>  Building for ispc-1.12.0
[1/166] cd /usr/ports/devel/ispc/work/ispc-1.12.0 && /usr/bin/m4 -Ibuiltins -DLLVM_VERSION=LLVM_8_0 -DBUILD_OS=UNIX -DRUNTIME=32 builtins/target-avx2-i32x4.ll | "/usr/local/bin/python3.7" bitcode2cpp.py builtins/target-avx2-i32x4.ll --runtime=32 --os=UNIX --llvm_as /usr/local/llvm80/bin/llvm-as > /usr/ports/devel/ispc/work/.build/./builtins-target-avx2-i32x4-32bit-unix.cpp
FAILED: builtins-target-avx2-i32x4-32bit-unix.cpp 
cd /usr/ports/devel/ispc/work/ispc-1.12.0 && /usr/bin/m4 -Ibuiltins -DLLVM_VERSION=LLVM_8_0 -DBUILD_OS=UNIX -DRUNTIME=32 builtins/target-avx2-i32x4.ll | "/usr/local/bin/python3.7" bitcode2cpp.py builtins/target-avx2-i32x4.ll --runtime=32 --os=UNIX --llvm_as /usr/local/llvm80/bin/llvm-as > /usr/ports/devel/ispc/work/.build/./builtins-target-avx2-i32x4-32bit-unix.cpp
/usr/local/llvm80/bin/llvm-as: <stdin>:10028:119: error: expected type
  %v_1 = call <4 x i32> @llvm.x86.avx2.gather.d.d(<4 x i32> undef, i8 * %ptr, <4 x i32> %offsets, <4 x i32> %vecmask, v1 1)
                                                                                                                      ^
[2/166] cd /usr/ports/devel/ispc/work/ispc-1.12.0 && /usr/bin/m4 -Ibuiltins -DLLVM_VERSION=LLVM_8_0 -DBUILD_OS=UNIX -DRUNTIME=32 builtins/target-avx2-i64x4.ll | "/usr/local/bin/python3.7" bitcode2cpp.py builtins/target-avx2-i64x4.ll --runtime=32 --os=UNIX --llvm_as /usr/local/llvm80/bin/llvm-as > /usr/ports/devel/ispc/work/.build/./builtins-target-avx2-i64x4-32bit-unix.cpp
FAILED: builtins-target-avx2-i64x4-32bit-unix.cpp 
cd /usr/ports/devel/ispc/work/ispc-1.12.0 && /usr/bin/m4 -Ibuiltins -DLLVM_VERSION=LLVM_8_0 -DBUILD_OS=UNIX -DRUNTIME=32 builtins/target-avx2-i64x4.ll | "/usr/local/bin/python3.7" bitcode2cpp.py builtins/target-avx2-i64x4.ll --runtime=32 --os=UNIX --llvm_as /usr/local/llvm80/bin/llvm-as > /usr/ports/devel/ispc/work/.build/./builtins-target-avx2-i64x4-32bit-unix.cpp
/usr/local/llvm80/bin/llvm-as: <stdin>:11972:119: error: expected type
  %v_1 = call <4 x i32> @llvm.x86.avx2.gather.d.d(<4 x i32> undef, i8 * %ptr, <4 x i32> %offsets, <4 x i32> %vecmask, v1 1)
                                                                                                                      ^
[3/166] cd /usr/ports/devel/ispc/work/ispc-1.12.0 && /usr/bin/m4 -Ibuiltins -DLLVM_VERSION=LLVM_8_0 -DBUILD_OS=UNIX -DRUNTIME=64 builtins/target-avx2-i32x4.ll | "/usr/local/bin/python3.7" bitcode2cpp.py builtins/target-avx2-i32x4.ll --runtime=64 --os=UNIX --llvm_as /usr/local/llvm80/bin/llvm-as > /usr/ports/devel/ispc/work/.build/./builtins-target-avx2-i32x4-64bit-unix.cpp
FAILED: builtins-target-avx2-i32x4-64bit-unix.cpp 
cd /usr/ports/devel/ispc/work/ispc-1.12.0 && /usr/bin/m4 -Ibuiltins -DLLVM_VERSION=LLVM_8_0 -DBUILD_OS=UNIX -DRUNTIME=64 builtins/target-avx2-i32x4.ll | "/usr/local/bin/python3.7" bitcode2cpp.py builtins/target-avx2-i32x4.ll --runtime=64 --os=UNIX --llvm_as /usr/local/llvm80/bin/llvm-as > /usr/ports/devel/ispc/work/.build/./builtins-target-avx2-i32x4-64bit-unix.cpp
/usr/local/llvm80/bin/llvm-as: <stdin>:10129:119: error: expected type
  %v_1 = call <4 x i32> @llvm.x86.avx2.gather.d.d(<4 x i32> undef, i8 * %ptr, <4 x i32> %offsets, <4 x i32> %vecmask, v1 1)
                                                                                                                      ^
[4/166] cd /usr/ports/devel/ispc/work/ispc-1.12.0 && /usr/bin/m4 -Ibuiltins -DLLVM_VERSION=LLVM_8_0 -DBUILD_OS=UNIX -DRUNTIME=32 builtins/target-avx2-i32x8.ll | "/usr/local/bin/python3.7" bitcode2cpp.py builtins/target-avx2-i32x8.ll --runtime=32 --os=UNIX --llvm_as /usr/local/llvm80/bin/llvm-as > /usr/ports/devel/ispc/work/.build/./builtins-target-avx2-i32x8-32bit-unix.cpp
FAILED: builtins-target-avx2-i32x8-32bit-unix.cpp 
cd /usr/ports/devel/ispc/work/ispc-1.12.0 && /usr/bin/m4 -Ibuiltins -DLLVM_VERSION=LLVM_8_0 -DBUILD_OS=UNIX -DRUNTIME=32 builtins/target-avx2-i32x8.ll | "/usr/local/bin/python3.7" bitcode2cpp.py builtins/target-avx2-i32x8.ll --runtime=32 --os=UNIX --llvm_as /usr/local/llvm80/bin/llvm-as > /usr/ports/devel/ispc/work/.build/./builtins-target-avx2-i32x8-32bit-unix.cpp
/usr/local/llvm80/bin/llvm-as: <stdin>:13603:123: error: expected type
  %v_1 = call <8 x i32> @llvm.x86.avx2.gather.d.d.256(<8 x i32> undef, i8 * %ptr, <8 x i32> %offsets, <8 x i32> %vecmask, v1 1)
                                                                                                                          ^
[5/166] cd /usr/ports/devel/ispc/work/ispc-1.12.0 && /usr/bin/m4 -Ibuiltins -DLLVM_VERSION=LLVM_8_0 -DBUILD_OS=UNIX -DRUNTIME=64 builtins/target-avx2-i64x4.ll | "/usr/local/bin/python3.7" bitcode2cpp.py builtins/target-avx2-i64x4.ll --runtime=64 --os=UNIX --llvm_as /usr/local/llvm80/bin/llvm-as > /usr/ports/devel/ispc/work/.build/./builtins-target-avx2-i64x4-64bit-unix.cpp
FAILED: builtins-target-avx2-i64x4-64bit-unix.cpp 
cd /usr/ports/devel/ispc/work/ispc-1.12.0 && /usr/bin/m4 -Ibuiltins -DLLVM_VERSION=LLVM_8_0 -DBUILD_OS=UNIX -DRUNTIME=64 builtins/target-avx2-i64x4.ll | "/usr/local/bin/python3.7" bitcode2cpp.py builtins/target-avx2-i64x4.ll --runtime=64 --os=UNIX --llvm_as /usr/local/llvm80/bin/llvm-as > /usr/ports/devel/ispc/work/.build/./builtins-target-avx2-i64x4-64bit-unix.cpp
/usr/local/llvm80/bin/llvm-as: <stdin>:12073:119: error: expected type
  %v_1 = call <4 x i32> @llvm.x86.avx2.gather.d.d(<4 x i32> undef, i8 * %ptr, <4 x i32> %offsets, <4 x i32> %vecmask, v1 1)
                                                                                                                      ^
[6/166] cd /usr/ports/devel/ispc/work/ispc-1.12.0 && /usr/bin/m4 -Ibuiltins -DLLVM_VERSION=LLVM_8_0 -DBUILD_OS=UNIX -DRUNTIME=64 builtins/target-avx2-i32x8.ll | "/usr/local/bin/python3.7" bitcode2cpp.py builtins/target-avx2-i32x8.ll --runtime=64 --os=UNIX --llvm_as /usr/local/llvm80/bin/llvm-as > /usr/ports/devel/ispc/work/.build/./builtins-target-avx2-i32x8-64bit-unix.cpp
FAILED: builtins-target-avx2-i32x8-64bit-unix.cpp 
cd /usr/ports/devel/ispc/work/ispc-1.12.0 && /usr/bin/m4 -Ibuiltins -DLLVM_VERSION=LLVM_8_0 -DBUILD_OS=UNIX -DRUNTIME=64 builtins/target-avx2-i32x8.ll | "/usr/local/bin/python3.7" bitcode2cpp.py builtins/target-avx2-i32x8.ll --runtime=64 --os=UNIX --llvm_as /usr/local/llvm80/bin/llvm-as > /usr/ports/devel/ispc/work/.build/./builtins-target-avx2-i32x8-64bit-unix.cpp
/usr/local/llvm80/bin/llvm-as: <stdin>:13728:123: error: expected type
  %v_1 = call <8 x i32> @llvm.x86.avx2.gather.d.d.256(<8 x i32> undef, i8 * %ptr, <8 x i32> %offsets, <8 x i32> %vecmask, v1 1)
                                                                                                                          ^
[7/166] cd /usr/ports/devel/ispc/work/ispc-1.12.0 && /usr/bin/m4 -Ibuiltins -DLLVM_VERSION=LLVM_8_0 -DBUILD_OS=UNIX -DRUNTIME=32 builtins/target-avx2-i32x16.ll | "/usr/local/bin/python3.7" bitcode2cpp.py builtins/target-avx2-i32x16.ll --runtime=32 --os=UNIX --llvm_as /usr/local/llvm80/bin/llvm-as > /usr/ports/devel/ispc/work/.build/./builtins-target-avx2-i32x16-32bit-unix.cpp
FAILED: builtins-target-avx2-i32x16-32bit-unix.cpp 
cd /usr/ports/devel/ispc/work/ispc-1.12.0 && /usr/bin/m4 -Ibuiltins -DLLVM_VERSION=LLVM_8_0 -DBUILD_OS=UNIX -DRUNTIME=32 builtins/target-avx2-i32x16.ll | "/usr/local/bin/python3.7" bitcode2cpp.py builtins/target-avx2-i32x16.ll --runtime=32 --os=UNIX --llvm_as /usr/local/llvm80/bin/llvm-as > /usr/ports/devel/ispc/work/.build/./builtins-target-avx2-i32x16-32bit-unix.cpp
/usr/local/llvm80/bin/llvm-as: <stdin>:17443:128: error: expected type
  %v1_1 = call <8 x i32> @llvm.x86.avx2.gather.d.d.256(<8 x i32> undef, i8 * %ptr, <8 x i32> %offsets_1, <8 x i32> %vecmask_1, v11 1)
                                                                                                                               ^
[8/166] cd /usr/ports/devel/ispc/work/ispc-1.12.0 && /usr/bin/m4 -Ibuiltins -DLLVM_VERSION=LLVM_8_0 -DBUILD_OS=UNIX -DRUNTIME=64 builtins/target-avx2-i32x16.ll | "/usr/local/bin/python3.7" bitcode2cpp.py builtins/target-avx2-i32x16.ll --runtime=64 --os=UNIX --llvm_as /usr/local/llvm80/bin/llvm-as > /usr/ports/devel/ispc/work/.build/./builtins-target-avx2-i32x16-64bit-unix.cpp
FAILED: builtins-target-avx2-i32x16-64bit-unix.cpp 
cd /usr/ports/devel/ispc/work/ispc-1.12.0 && /usr/bin/m4 -Ibuiltins -DLLVM_VERSION=LLVM_8_0 -DBUILD_OS=UNIX -DRUNTIME=64 builtins/target-avx2-i32x16.ll | "/usr/local/bin/python3.7" bitcode2cpp.py builtins/target-avx2-i32x16.ll --runtime=64 --os=UNIX --llvm_as /usr/local/llvm80/bin/llvm-as > /usr/ports/devel/ispc/work/.build/./builtins-target-avx2-i32x16-64bit-unix.cpp
/usr/local/llvm80/bin/llvm-as: <stdin>:17616:128: error: expected type
  %v1_1 = call <8 x i32> @llvm.x86.avx2.gather.d.d.256(<8 x i32> undef, i8 * %ptr, <8 x i32> %offsets_1, <8 x i32> %vecmask_1, v11 1)
                                                                                                                               ^
ninja: build stopped: subcommand failed.
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1
```

FreeBSD 12, in the ports framework

**Comment by dbabokin** [comment]
Is there a way to reproduce it in Docker?

**Comment by dbabokin** [comment]
One thing that stands out - we use python 2.7 in ispc 1.12.0, while you are using 3.7, though in this case it might be not a problem.

**Comment by yurivict** [comment]
Which version of LLVM do you use? I get this error with both llvm-80 an llvm-90.

**Comment by dbabokin** [comment]
1.12.0 works with LLVM 6.0-9.0
trunk works with LLVM 6.0-11.0 (trunk)

**Comment by yurivict** [comment]
This m4 command produces invalid types ```v1``` and ```v11```.

```
/usr/bin/m4 -Ibuiltins -DLLVM_VERSION=LLVM_9_0 -DBUILD_OS=UNIX -DRUNTIME=64 builtins/target-avx2-i32x16.ll
```

**Comment by dbabokin** [comment]
v1 and v11 are variables, not types. What m4 version are you using?

**Comment by yurivict** [comment]
It was an outdated m4, thanks!

**Comment by myfreeweb** [comment]
> It was an outdated m4, thanks!

Not outdated, but non-GNU. Having more than 9 arguments in a macro is a GNU extension.
