### ISSUE TITLE
Fatal error on (I think) pointer-to-pointer in ISPC 1.25.3

### ISSUE THREAD

**Issue by athas** [ispc/ispc#3202]
This contrived program causes ISPC 1.25.3 to crash:

```ispc
uniform int** f(uniform int** p) { }
```

```
$ ispc bug.ispc
Warning: No output file or header file name specified. Program will be compiled and
        warnings/errors will be issued, but no output will be generated.
Warning: No --target specified on command-line. Using default system target
        "avx2-i32x8".
/build/source/src/module.cpp:1242: Assertion failed: "decl && decl->functionParams.size() == nArgs".
***
*** Please file a bug report at https://github.com/ispc/ispc/issues
*** (Including as much information as you can about how to reproduce this error).
*** You have apparently encountered a bug in the compiler that we'd like to fix!
***
/build/source/src/main.cpp(414): FATAL ERROR: Unhandled signal sent to process; terminating.
Aborted (core dumped)
```

This is as small as I could make the program. The problem is unrelated to the empty function body.

**Comment by nurmukhametov** [comment]
This was introduced in https://github.com/ispc/ispc/commit/bd6d0ffea231a1fabb73d1ab4e8f65eed6deb65e.

I also need to note that the type `uniform int**` is actually `uniform int * uniform * varying`.
