### ISSUE TITLE
Examples fail to compile on Ubuntu 12.04

### ISSUE THREAD

**Issue by ezschemi** [ispc/ispc#303]
I have installed LLVM/Clang 3.1 and compiled ispc from git. ispc compile is fine, compiling all of the examples fails with: 

[ 15:42:01  rt ] : pwd
/home/ezschemi/projects/ispc/examples/rt
[ 15:42:01  rt ] : make
/bin/mkdir -p objs/
ispc -O2 --arch=x86-64  --target=sse2,sse4-x2,avx rt.ispc -o objs/rt_ispc.o -h objs/rt_ispc.h
builtins.cpp:683: Assertion failed: "func != NULL".

---

**\* Please file a bug report at https://github.com/ispc/ispc/issues
**\* (Including as much information as you can about how to reproduce this error).
**\* You have apparently encountered a bug in the compiler that we'd like to fix!

---

main.cpp(204): FATAL ERROR: Unhandled signal sent to process; terminating.
make: **\* [objs/rt_ispc.h] Aborted (core dumped)

The Ubuntu is up to date.
