### ISSUE TITLE
rdtsc() linker error

### ISSUE THREAD

**Issue by FattiMei** [ispc/ispc#2677]
I want to compile this test program (the `timing.h` file is the one in `ispc/examples/common`)

```c
#include "timing.h"

int main(){
	reset_and_start_timer();
	double t = get_elapsed_mcycles();

	return 0;
}
```

with a C compiler (it should be possible, right?).
Both gcc and clang produce the same linker error:
```
undefined reference to rdtsc
```
The compilation commands were
```
gcc -o test main.c
clang -o test main.c
```

I have Ubuntu version 20.04.6 LTS on a x86 machine, gcc version 9.4.0, clang version 10.0.0

**Comment by nurmukhametov** [comment]
Add `-O2` to compilation command.

**Comment by FattiMei** [comment]
Ok, it works. But isn't bad practice when the code doesn't compile on debug mode? Just asking, I'm a newbie :)

**Comment by nurmukhametov** [comment]
If you really don't want to add `-O2` then you may add `static` keyword to `rdtsc` function declaration in `timing.h`. It should work as well.

**Comment by FattiMei** [comment]
So, should I make a pull request to fix this issue, or simply close it?

**Comment by nurmukhametov** [comment]
I prefer to let it be as is so no fix is required here in my opinion.
