### ISSUE TITLE
ispc fails to build with 12.0.d20200811: error: no member named 'get' in 'llvm::ElementCount'

### ISSUE THREAD

**Issue by yurivict** [ispc/ispc#1870]
```
/usr/ports/devel/ispc/work/ispc-1.14.1/src/ctx.cpp:1690:33: error: no member named 'get' in 'llvm::ElementCount'
            llvm::ElementCount::get(static_cast<unsigned int>(g->target->getVectorWidth()), false), const_val);
            ~~~~~~~~~~~~~~~~~~~~^
/usr/ports/devel/ispc/work/ispc-1.14.1/src/ctx.cpp:3155:60: error: no member named 'get' in 'llvm::ElementCount'
        llvm::ConstantVector::getSplat(llvm::ElementCount::get(static_cast<unsigned int>(ty->getNumElements()), false),
                                       ~~~~~~~~~~~~~~~~~~~~^
2 errors generated.
```

**Comment by dbabokin** [comment]
ISPC builds with LLVM trunk nightly, 20200811 is too old. I.e. it's known to contain incompatible changes and there's no way we can build with *both* LLVM 20200811 snapshot and trunk.
