### ISSUE TITLE
ISPC 1.13 oes not work on Mac OS X El Capitan (10.11)

### ISSUE THREAD

**Issue by ColinChargyBentley** [ispc/ispc#1737]
Hi,
The ISPC binaries from the release page does not work with Mac OS X El Capitan (10.11) with the following error:
```
dyld: lazy symbol binding failed: Symbol not found: __ZNSt3__118shared_timed_mutexC1Ev
  Referenced from: ispc
  Expected in: /usr/lib/libc++.1.dylib

dyld: Symbol not found: __ZNSt3__118shared_timed_mutexC1Ev
  Referenced from: ispc
  Expected in: /usr/lib/libc++.1.dylib
```

Regards,
Colin Chargy

**Comment by dbabokin** [comment]
Generally, developers stay on relatively new platforms. So my approach for the releases is that "latest version - 1" is good enough. Latest is Catalina 10.15. Release is built on Mojave 10.14. Let me check if I have that old OS around to build on.

What platforms are you targeting (both hardware and software)?

**Comment by ColinChargyBentley** [comment]
Hi,
We're building our soft on MacPro late 2013 under Mac OS X El Capitan (10.11). Our software is officially supported on 10.10.

Does code compiled with ISPC on MacOS have a limited range of supported version of MacOS or is there only constrains on computer running ISPC ? In other words, does ISPC constraint version of MacOS only for compiling the code or also to run it ?

Regards,
Colin Chargy

**Comment by dbabokin** [comment]
ISPC generated code doesn't have dependency on macOS version, unless you have print() in your code (which needs to link with libc implementation in system library).
I haven't found machine with 10.11 so far, but will check couple more places.
In the meantime you can use the version built by brew: `brew install ispc`. Brew builds not the way we recommend to build, but for 1.13 it should be good enough if you are not cross compiling (brew version is not a cross compiler).

**Comment by dbabokin** [comment]
I managed to find macOS 10.12 to build the release. There's a slight chance that these binaries will work on 10.11. Could you give it a try?

[Archive is here](https://drive.google.com/open?id=1io49Q_soL7nY7kkhnQZE681kO1-3Y4x5)

**Comment by ColinChargyBentley** [comment]
Hi @dbabokin,
The binaries you provided does not work on 10.11 :
```
dyld: lazy symbol binding failed: Symbol not found: __ZNSt3__118shared_timed_mutexC1Ev
  Referenced from: /Volumes/Crypted/SlaveCheck/vue.git/LRTu15/Vue/Source/Extern/IntelSPMDProgramCompiler/ispc_macos (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libc++.1.dylib

dyld: Symbol not found: __ZNSt3__118shared_timed_mutexC1Ev
  Referenced from: /Volumes/Crypted/SlaveCheck/vue.git/LRTu15/Vue/Source/Extern/IntelSPMDProgramCompiler/ispc_macos (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libc++.1.dylib
```

Thanks for trying.
I'll build ISPC with brew then,
Regards,
Colin Chargy

**Comment by dbabokin** [comment]
It might be tricky to build it on 10.11, I'm not sure they'll do that (I can't verify it from later OS). The problem is that building LLVM 10.0 on early versions of OS is not straightforward - it requires newer compiler. So for 10.12 I had to build LLVM 8.0 and then LLVM 10.0 using 8.0.

If I have time, I'll reformat my old machine to El Capitan and build ISPC there.

**Comment by dbabokin** [comment]
I've built 1.13.0 release on macOS 10.10 Yosemite. @ColinChargyBentley, could you try it https://drive.google.com/open?id=1NxNMLK1HU_GMPf9952HWpHo4U3_3f6Tp ? If it works well for you, I'll publish it on Github Releases.

In case someone would like to build ISPC on old macOS, here's what needed on 10.10:
- xcode command line tools: ``xcode-select --install``
- cmake and python3 (downloaded manually)
- bison (I've used the latest, 3.6), download sources and build manually.
- LLVM needs to be bootstrapped in several steps. LLVM 6 -> LLVM 8 -> LLVM 10. Note, on 10.12 I managed to do just LLVM 8 -> LLVM 10.

**Comment by ColinChargyBentley** [comment]
Hi @dbabokin ,
The build you've provided works like a charm.
Thank you
Colin Chargy

**Comment by ColinChargyBentley** [comment]
Hi @dbabokin,
Is it possible to have the same kind of build of ISPC 1.14.1 for older MacOS version ?
Regards,
Thanks,
Colin Chargy

**Comment by dbabokin** [comment]
macOS builds for v1.14.1 and v1.15.0 should support macOS 10.10. After you request I started building releases on 10.10. Do you have problem with these builds?

Going forward we will have to move to newer macOS (probably 10.12), because building modern LLVM for old macOS (specifically 10.10 and older) is not supported any more.

Do you have plans to retire support for macOS 10.10?

**Comment by ColinChargyBentley** [comment]
Hi @dbabokin ,
Indeed, the binary you provided are fine, thanks. Yes, we need to retire support of older MacOS, we will do that in the future.
Thank you
Regards,
Colin Chargy
