### ISSUE TITLE
this->size() assert error

### ISSUE THREAD

**Issue by ndowens** [ispc/ispc#2192]
While trying to compile openvkl, which uses ispc, I am getting
`/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/bits/stl_vector.h:1045: std::vector::reference std::vector<llvm::Constant *>::operator[](std::vector::size_type) [_Tp = llvm::Constant *, _Alloc = std::allocator<llvm::Constant *>]: Assertion '__n < this->size()' failed.
/build/ispc/src/ispc-1.16.1/src/main.cpp(392): FATAL ERROR: Unhandled signal sent to process; terminating.
`

Here is the full build output:
https://dpaste.org/ULAH

**Comment by dbabokin** [comment]
I do OpenVML superbuild on Ubuntu 20.04 and it works fine.

Looks like there are some problems with ISPC binary running in your environment, which is strange as we link statically as much as possible for the release:
```
> ldd ispc
        linux-vdso.so.1 (0x00007ffc215f1000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa597820000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa5977fd000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa5976ae000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa5974bc000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa597845000)
```

So, are you using ISPC from the Github release downloads (i.e. from here https://github.com/ispc/ispc/releases/tag/v1.16.1) or build it yourself?

Can you compile a dummy ispc file with your ISPC binary? (say, a file with single `;` in it).

Do you have a Dockerfile that reproduces your environment?

**Comment by ndowens** [comment]
It looks like it using archive/v$pkgver/$pkgname-$pkgver.tar.gz
Here is the PKGBUILD https://gitea.artixlinux.org/packagesI/ispc/src/branch/master/trunk/PKGBUILD

Results from a test.ispc with just a ; in it
`Warning: No output file or header file name specified. Program will be compiled and warnings/errors will be issued, but no output will be generated. 
Warning: No --target specified on command-line. Using default system target "avx2-i32x8". 
➜  ~ ispc test.ispc -o test
Warning: No --target specified on command-line. Using default system target "avx2-i32x8". `

I don't have a dockerfile. The weird part is, it is the same as Arch and AFAIK we use the same flags Arch uses

**Comment by dbabokin** [comment]
ISPC is able to compile a dummy file. But the problem seem to be in the way it was built and linked and I have no control over it nor understand how Arch builds it.

I guess the way forward is to isolate a single compile command and try debugging it or reducing the file. Though seems that the problem is in argument parsing.

I would also check what stdlibc++ it was build against and how it compares to what you have on the system - as the problem somehow related to C++ library.

And you can download an official release and verify that it work in the same environment.

**Comment by ndowens** [comment]
Update, ISPC precompiled works. What CFLAGS/CXXFLAGS does ISPC precompiled use?

**Comment by ndowens** [comment]
Update2: Fixed it, seems it was a flag issue. Thanks for your help

**Comment by ArchangeGabriel** [comment]
@ndowens What flags did you change and how?

**Comment by ArchangeGabriel** [comment]
Ah, you actually removed all flags (https://gitea.artixlinux.org/packagesI/ispc/commit/cd07ccca77ea9bfa4d2ecff8ba5a348e0fd9f5e6). I guess I’ll have to bisect the flags.
