### ISSUE TITLE
ISPC 1.21 "FNeg operator only works with float types" 

### ISSUE THREAD

**Issue by petrsm** [ispc/ispc#2628]
Compiling this code:

typedef float<2> float2;

float2 TestFunc(float2 x)
{
 	return -x;
}

results in following error message:

FNeg operator only works with float types!
  %13 = fneg [2 x <8 x float>] %12
LLVM ERROR: Broken module found, compilation aborted!
D:\actions-runner\intel\001\_work\applications.compilers.ispc.core\applications.compilers.ispc.core\src\main.cpp(404): FATAL ERROR: Unhandled signal sent to process; terminating.

**Comment by aneshlya** [comment]
Thanks for reporting this. The regression happened after commit 8de98b4c3.
