### ISSUE TITLE
Crash with static mask variable

### ISSUE THREAD

**Issue by emoon** [ispc/ispc#3086]
Given the following code

```C
static const varying int shuffle_color_mask = { 0, 1, 2, 3, 0, 1, 2, 3,  0, 1, 2, 3, 0, 1, 2, 3 };
````

Compiled with `-O2 --target=sse4.2-i16x8` gives the following error

```
malloc(): corrupted top size
/usr/local/src/ispc/src/main.cpp(414): FATAL ERROR: Unhandled signal sent to process; terminating.
***
*** Please file a bug report at https://github.com/ispc/ispc/issues
*** (Including as much information as you can about how to reproduce this error).
*** You have apparently encountered a bug in the compiler that we'd like to fix!
***
Program terminated with signal: SIGSEGV
Compiler returned: 139
```
```
ipsc --version
Intel(r) Implicit SPMD Program Compiler (Intel(r) ISPC), 1.25.1 (build commit 7846682383ec382a @ 20241016, LLVM 18.1.8)
```

https://godbolt.org/z/661P8M3vb

**Comment by aneshlya** [comment]
Regression after https://github.com/ispc/ispc/pull/2739
